# Generated by Django 4.2.5 on 2023-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=256)),
                ("bus_sacco", models.CharField(max_length=256)),
                ("driver_id", models.IntegerField()),
                ("route", models.CharField(max_length=256)),
            ],
        ),
    ]
