# Generated by Django 4.2.5 on 2023-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_worldborder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorldBorder",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="location",
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
