# Generated by Django 4.2.5 on 2023-11-20 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_delete_worldborder_remove_vehicledetail_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicledetail",
            name="driver_id",
        ),
    ]
