# Generated by Django 4.2.5 on 2023-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=256)),
                ("start", models.CharField(max_length=256)),
                ("stop", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="StopDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.CharField(max_length=256)),
                ("stop_name", models.CharField(blank=True, max_length=256)),
                ("stop_latitude", models.IntegerField(default=0)),
                ("stop_longitude", models.IntegerField(default=0)),
            ],
        ),
    ]
