# Generated by Django 4.2.5 on 2023-11-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routedetail",
            name="route_id",
            field=models.IntegerField(default=0),
        ),
    ]
