# Generated by Django 4.2.5 on 2023-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_routedetail_route_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StopDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="routedetail",
            name="route_id",
            field=models.CharField(max_length=256),
        ),
    ]
