# Generated by Django 4.2.5 on 2023-11-04 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0003_stopdetails_alter_routedetail_route_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StopDetails",
            new_name="StopDetail",
        ),
    ]
