# Generated by Django 4.2.5 on 2023-11-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0004_rename_stopdetails_stopdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stopdetail",
            old_name="stop",
            new_name="stop_id",
        ),
        migrations.AddField(
            model_name="stopdetail",
            name="stop_latitude",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stopdetail",
            name="stop_name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
