# Generated by Django 4.2.5 on 2023-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassengerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("isincar", models.BooleanField()),
                ("location", models.CharField(max_length=256)),
            ],
        ),
    ]
